# Generated by Django 5.1.5 on 2025-01-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date creation'),
        ),
    ]
